FROM node:alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install -g @nestjs/cli prisma
RUN npm install --omit=dev

COPY . .

EXPOSE 3000
CMD ["sh", "-c", "npx prisma migrate dev && npm run start:dev"]
