FROM node:alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install -g @nestjs/cli prisma
RUN npm install

COPY . .

EXPOSE 3000
CMD ["sh", "-c", "npx prisma db push && npm run start:dev"]
